### ISSUE TITLE
Support for Server Name Indication (SNI) when connecting through TLS

### ISSUE THREAD

**Issue by PaulaFernandez** [tomerfiliba-org/rpyc#468]
Hi, 

I'm running several rpyc projects inside docker and I'm trying to route connections to them with [Traefik](https://traefik.io/), but for that to work in the scenario I need, I would need rpyc to support SNI.

Currently rpyc uses `ssl.wrap_socket(sock, **kwargs)`, which has been deprecated.

https://docs.python.org/dev/library/ssl.html#ssl.wrap_socket

> Deprecated since version 3.7: Since Python 3.2 and 2.7.9, it is recommended to use the SSLContext.wrap_socket() instead of wrap_socket(). The top-level function is limited and creates an insecure client socket without server name indication or hostname matching.

The recommended method to use, `SSLContext.wrap_socket`, appears to have the functionality I need.

https://docs.python.org/dev/library/ssl.html#ssl.SSLContext.wrap_socket

> On client connections, the optional parameter server_hostname specifies the hostname of the service which we are connecting to. This allows a single server to host multiple SSL-based services with distinct certificates, quite similarly to HTTP virtual hosts. Specifying server_hostname will raise a ValueError if server_side is true.

The main problem is Traefik won't work with HostSNI set to anything different `HostSNI(`*`)` for rpyc projects.

I understand this won't be a priority but I thought to raise it just in case someone else is interested (or knows a workaround).

I have a test project here: https://github.com/PaulaFernandez/rpyc-tls and some details also below:

##### Environment

- rpyc version: 5.0.1
- python version: 3.8.12
- operating system: Docker version 20.10.8 for MAC

##### Minimal example
Dockerfile:

```
FROM python:3.8-slim-buster as python-base

    # python
ENV PYTHONUNBUFFERED=1 \
    # prevents python creating .pyc files
    PYTHONDONTWRITEBYTECODE=1 \
    \
    # pip
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100 \
    \
    # poetry
    # https://python-poetry.org/docs/configuration/#using-environment-variables
    POETRY_VERSION=1.0.10 \
    # make poetry install to this location
    POETRY_HOME="/opt/poetry" \
    # do not create virtual environments
    POETRY_VIRTUALENVS_CREATE=false \
    # do not ask any interactive question
    POETRY_NO_INTERACTION=1 

# Prepend poetry and venv to path
ENV PATH="$POETRY_HOME/bin:$PATH"

# `builder-base` stage is used to build deps + create our virtual environment
FROM python-base as builder-base
RUN apt-get update \
    && apt-get install --no-install-recommends -y \
        # deps for installing poetry
        curl \
        # deps for building python deps
        build-essential \
        # ssh-scan to add gitlab
        ssh \
        # git so we can install git dependencies
        git

# Install poetry - respects $POETRY_VERSION & $POETRY_HOME - and configure package repository credentials
RUN curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python

# Copy project requirement files here to ensure they will be cached.
WORKDIR /app
COPY pyproject.toml poetry.lock ./

# Install runtime deps - uses $POETRY_VIRTUALENVS_IN_PROJECT internally
RUN poetry update -vvv

COPY . /app

RUN poetry install

CMD python tpyc_tls/server.py
```

docker-compose:

```
version: "3.7"

services:
  gecco:
    build: ./
    container_name: gecco
    restart: unless-stopped
    expose:
      - "18862"
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.gecco.entrypoints=rpc"
      - "traefik.tcp.routers.gecco.rule=HostSNI(`*`)"
      # - "traefik.tcp.routers.gecco.rule=HostSNI(`gecco.company.com`)"
      - "traefik.tcp.routers.gecco.service=gecco"
      - "traefik.tcp.services.gecco.loadbalancer.server.port=18862"
      - "traefik.tcp.routers.gecco.tls=true"
      - "traefik.tcp.routers.gecco.tls.passthrough=true"
    volumes:
      - $HOME/certs:/certs/
    networks:
      - company-network

networks:
  company-network:
    external:
      name: company-network
```

Server:

```python
import rpyc
from rpyc.utils.server import ThreadedServer
from rpyc.utils.authenticators import SSLAuthenticator

class DictionaryService(rpyc.Service):
    def exposed_test(self, a):
        return {"arg": a}

if __name__ == "__main__":
    authenticator = SSLAuthenticator(
        keyfile="/certs/gecco.key",
        certfile="/certs/gecco.crt"
    )

    server = ThreadedServer(
        DictionaryService,
        port=18862,
        protocol_config={"allow_public_attrs": True},
        authenticator=authenticator
    )
    server.start()
```

Client:

```python
import rpyc

def test_server():
    c = rpyc.ssl_connect(
        "gecco.colorifix.com",
        port=18861,
        keyfile="/path_to_certs/certs/client.key",
        certfile="/path_to_certs/certs/certs/client.crt",
        ssl_version=2
    )
    ret = c.root.test("54")
    print(ret["arg"])

if __name__ == "__main__":
    test_server()
```
